### ISSUE TITLE
Option pour cacher scénarios dans widget

### ISSUE THREAD

**Issue by Juju31Fr** [mguyard/Jeedom-Diagral_eOne#3]
Pour les utilisateurs qui n'utilisent pas les scénarios Diagral, ajouter une option permettant de cacher la partie correspondante du widget.

**Comment by mguyard** [comment]
**Howto :**

Ajouter un id sur le select (ex. cmd#launch_scenario_id#Scenario) :
`<select class="selectCmd form-control form-control-lg" title="Scenarios" id=" cmd#launch_scenario_id#Scenario">#launch_scenario_listValue#</select>`

Ajouter ensuite une verification pour cacher le scenario si aucun scénario existe (donc 1 seule option dans le select) :

if ( $('#cmd#launch_scenario_id#Scenario option').length == 1) {
   $('.Diagral_eOne_widget').css('height', 'XXXpx'); # Change la taille de la tuile
   $( "#scenarios" ).hide(); # Cache la partie Scenario
}
