### ISSUE TITLE
[BUG] JEEDOMErreur sur Diagral_eOne::pull() : Unable to connect to Diagral Cloud after 1 attempts. Please verify your internet connection and/or retry later.

### ISSUE THREAD

**Issue by PowerOfSun44** [mguyard/Jeedom-Diagral_eOne#36]
Version appli jeedom: 2021-09-17 - v2.3.4

**Description du bug**
j'ai régulièrement l'erreur suivante avec plusieurs récurrences par jour:
`Erreur sur Diagral_eOne::pull() : Unable to connect to Diagral Cloud after 1 attempts. Please verify your internet connection and/or retry later.`

**Comment reproduire**
je ne sais pas.. je ne comprends pas pourquoi j'ai cette erreur et comment la résoudre ?

**Resultat Normal Attendu**
Une description claire et concise de résultat attendu

**Screenshots**
Ajouter des screenshot si possible dans le contexte

**Versions:**
 - OS: Debian sur Raspberry pi
 - Browser chrome
 - Version Jeedom 4.1.20

**Informations additionnellees**
 je ne comprends pas pourquoi j'ai cette erreur et comment la résoudre ?
merci

**Comment by mguyard** [comment]
Bonjour,

Le souci provient d'un problème de connexion au Cloud Diagral.
Cela peut avoir plusieurs raisons :

- Votre accès internet n'est pas opérationnel
- Le cloud Diagral rencontre un souci

Le Cloud Diagral a plusieurs fois par jours des instabilités qui peuvent retourner ce type d'erreur.
Vous pouvez modifier la configuration du plugin pour faire plus de tentative avant de retourner le message :

![image](https://user-images.githubusercontent.com/5262395/146425285-4fed27eb-5776-4731-8981-5d957299c321.png)

**Comment by PowerOfSun44** [comment]
Bonjour,

Merci Marc, je suis en connexion 4G c'est probablement due à ça ou sinon le cloud.

Merci en tout cas.
