### ISSUE TITLE
[FEATURE] File missing knx-garage_door.config.json

### ISSUE THREAD

**Issue by guielec42** [mguyard/Jeedom-Diagral_eOne#40]
Même soucis STABLE ou BETA

**Description du bug**
Un fois le code de la centrale renseigné j'ai le méssage d'erreur

[2023-05-07 08:18:43]ERROR : Impossible de trouver le fichier de configuration '/var/www/html/plugins/Diagral_eOne/core/config/cmdConfig/knx-garage_door.config.json'

**Comment reproduire**
Etapes pour reproduire le comportement:
Install fraiche avec portainer en utilisant le jeedom/jeedom:4.3
ajout du plugin
reseigner identifiant
synchro
renseigne code centrale
synchro (et ici ca bug)

**Resultat Normal Attendu**
Une description claire et concise de résultat attendu

**Screenshots**
Ajouter des screenshot si possible dans le contexte

**Versions:**
 - OS: docker
 - Browser firefox
 - Version Jeedom  4.4.0 et  4.3.2

**Comment by mguyard** [comment]
Bonjour,

Ce n'est pas un bug, d'où la reclassification de cette issue.

Actuellement le garage n'est supporté qu'en mode Adyx.
Sur Knx, seul les volets et lumières sont supportés comme l'indique la documentation
![CleanShot 2023-05-07 at 12 37 48](https://user-images.githubusercontent.com/5262395/236672598-7a07abc4-6d61-4245-8ab3-4edbfda76594.png)

Je viens de créer un issue pour retourner un message indiquant que ce n'est pas un module supporté lorsque cela arrive : https://github.com/mguyard/Jeedom-Diagral_eOne/issues/41

N'ayant pas ce module, je ne sais pas si il se comporte comme l'Adyx.
Il est facile de le tester en copiant le fichier adyx-garage_door.config.json qui est dans le dossier /var/www/html/plugins/Diagral_eOne/core/config/cmdConfig/ en le nommant avec le nom knx-garage_door.config.json

Cela devrait à la suite d'une sauvegarde du module KNX, créer une commande **Mouvement** qu'il faudra tester pour valider le fonctionnement.

- Dans le cas d'un fonctionnement validé, j'ajouterais le fichier dans une prochaine mise à jour. 
- Dans le cas contraire, je n'aurais pas le temps de travailler sur l'analyse du fonctionnement de ce module (comme aucune API n'existe chez Diagral, seul du reverse engineering le permet) et donc ce module ne sera pas intégré à moins que quelqu'un fasse l'analyse et me fasse un PR

**Comment by guielec42** [comment]
Bonjour,

J'admire le travail réalisé. Je me suis inscris pour avoir accès aux API,
mais rien n'y fait, pas de réponse au mail...
Je tourne sous home assistant, je vais avoir un docker jeedom pour piloter
l'alarme, c'est pas très beau mais ça fera l'affaire.
Chapeau pour le reverse engineering, faut être patient.
En ayant renommé le fichier ca marche, merci.

Bien cordialement,
Guillaume

**Comment by mguyard** [comment]
Je vais sortir une beta avec le fichier alors identique à adyx.
Je suis aussi en plein switch HA et je verrais pour une intégration quand mon switch sera fini.
Pour l'instant j'appelle Jeedom par API avec le sensor rest pour activation/désactivation/presence

**Comment by guielec42** [comment]
Ça fonctionne avec les API Jeedom mais au bout de 24H je suis bloqué par
diagral.
Je suis obligé de changer de mot de passe pour débloquer la situation.
Comment avez-vous configuré le module de votre côté ?
[image: image.png]

|[Erreur] Diagral_eOne::pull() : Unable to connect to Diagral Cloud
after 1 attempts. Please verify your internet connection and/or retry
later.

[image: image.png]

**Comment by mguyard** [comment]
Diagral bloque si le/les comptes associés à l'alarme font plus de 15 requetes par heures glissante. Il ne faut donc pas mettre un refresh trop agressif
