### ISSUE TITLE
[QUESTION] Quel statut quand l'alarme sonne ?

### ISSUE THREAD

**Issue by Aymkdn** [mguyard/Jeedom-Diagral_eOne#46]
Bonjour,

Sais-tu si un statut particulier est retourné lorsque l'alarme est en train de sonner ? ([référence](https://github.com/mguyard/Jeedom-Diagral_eOne/blob/0a1193ff6f65300a9e540d9cd866997524c187df/3rparty/Diagral-eOne-API-PHP/class/Diagral/Diagral_eOne.class.php#L581))

Il est indiqué que `le statut peut être "off", "group", "tempogroup", "presence", ou "on"`, mais comment peut-on savoir que l'alarme a détecté quelque chose ? Ou bien faut-il regarder à chaque fois [les events](https://github.com/mguyard/Jeedom-Diagral_eOne/blob/0a1193ff6f65300a9e540d9cd866997524c187df/core/class/Diagral_eOne.class.php#L1243) ? Ou autre chose ?

Merci

**Comment by mguyard** [comment]
Bonjour,

Tout est indiqué dans la doc https://mguyard.github.io/Jeedom-Documentations/fr_FR/Diagral_eOne/documentation#Déclenchement%20d’alarme

Cependant comme Diagral a retiré les emails, ce n'est plus possible. Les SMS n'ayant jamais était intégré car je n'ai pas la passerelle. Toutefois, ça pourrait être intégré manuellement avec un plugin qui collecte le SMS et si ça correspond à un déclenchement d'alarme, avec un scénario qui lance un event vers la commande on peut dire au plugin que l'alarme s'est déclenché.

Tout est expliqué dans la doc pour permettre de mettre en place par SMS au besoin manuellement.

**Comment by Aymkdn** [comment]
OK, merci pour la réponse rapide !
