### ISSUE TITLE
[BUG] Erreur 500 sur Génération automatique du scénario

### ISSUE THREAD

**Issue by marcantoinegodde** [mguyard/Jeedom-Diagral_eOne#50]
**Description du bug**
Lorsque je clique sur le bouton de génération automatique du scénario, Jeedom me renvoie une erreur 500.

**Comment reproduire**
Etapes pour reproduire le comportement:
1. Dans "Notifications Diagral", je choisis "#[Email][Mail Alarme]#"
2. Je clique sur "Génération automatique du scénario"
3. J'obtiens un bandeau "500 : Internal Server Error"

**Resultat Normal Attendu**
Pas d'erreur et génération du scénario

**Screenshots**
<img width="1220" alt="Screenshot 2024-10-09 at 10 17 52" src="https://github.com/user-attachments/assets/c86bbd7a-eedf-4ce8-a079-a88f96933896">

**Versions:**
 - OS: Debian
 - Browser Safari
 - Version Jeedom 4.4.12
 - Plugin Diagral 2024-09-16 16:55:09

**Informations additionnellees**
Dans le `http.error`, j'obtiens cette erreur:
```
[Wed Oct 09 09:50:47.046967 2024] [php7:error] [pid 2069:tid 2069] [client 192.168.1.100:51204] PHP Fatal error:  Uncaught Error: Call to a member function getHumanName() on bool in /var/www/html/plugins/Diagral_eOne/core/ajax/Diagral_eOne.ajax.php:277\nStack trace:\n#0 {main}\n  thrown in /var/www/html/plugins/Diagral_eOne/core/ajax/Diagral_eOne.ajax.php on line 277, referer: http://192.168.1.100/index.php?v=d&m=Diagral_eOne&p=Diagral_eOne&id=29
[Wed Oct 09 09:55:20.093048 2024] [php7:error] [pid 975:tid 975] [client 192.168.1.100:33538] PHP Fatal error:  Uncaught Error: Call to a member function getHumanName() on bool in /var/www/html/plugins/Diagral_eOne/core/ajax/Diagral_eOne.ajax.php:277\nStack trace:\n#0 {main}\n  thrown in /var/www/html/plugins/Diagral_eOne/core/ajax/Diagral_eOne.ajax.php on line 277, referer: http://192.168.1.100/index.php?v=d&m=Diagral_eOne&p=Diagral_eOne&id=29
```

**Comment by mguyard** [comment]
Bonjour,

Cette partie n'est pas maintenue car Diagral n'envoi plus de mail.
Ceci est indiqué dans la documentation : https://mguyard.github.io/Jeedom-Documentations/fr_FR/Diagral_eOne/documentation#A%20r%C3%A9ception%20d%E2%80%99un%20Email%20ou%20SMS

Je ne l'ai pas retiré car j'évite le maximum de changements sur ce plugin pour eviter de le casser, vu qu'il va dans le temps devenir obsolete pour être surement replacé par un nouveau plugin : https://community.jeedom.com/t/message-diagral-demandant-la-raison-de-nombreuses-connexions/82880/91?u=mguyard
